
import "./globals.css";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="font-nunito bg-[#202c37] pt-[6rem]">
        <header className="fixed top-0 left-0 right-0 bg-[#202c37] text-white z-50 w-full font-nunito flex flex-col gap-11 pb-[20px]">
          <nav className="flex flex-row justify-start w-full bg-[#2b3945] text-white  p-5 font-semibold text-[1.4rem] shadow-md">
              <h1>Where in the world ?</h1>
          </nav>
          
        </header>
        {children}
      </body>
    </html>
  );
}
